import math
from random import random

templates = [
   	'A noun1 searching for the noun2 beehind the adj1 noun3',
	'The noun1 lost in the adj1 noun2 hoping for the adj2 noun3',
    'Beehold. adj1. noun1. Are you ready?',
	'In the bowels of a noun1 there lies a adj1 noun2',
	'Forever lost in a adj1 noun1, nothing will ever bee the same',
	'Bound by a noun1, noun2 lurks in the shadows',
	'A adj1, adj2, noun1 sits in the middle of this hive',
	'There is noun1 all around you making a adj1 sound',
	'Kowabunga, you stepped in a steaming pile of adj1 noun1',
	'Son a Bee***, this planet smells of adj noun1',
	'The adj1 of the galaxy. Stay away from the adj1 noun1',
	'A adj1 type hive... how interesting',
	'A adj1 noun1 wants you to run away and never return',
	'The noun1 found a noun2 underneath a adj1 adj2 noun3... weird',
	"Don't you wish a noun1 would just drop a adj1 noun2?",
	"A fortnite ago, this place was a adj adj2 noun1",
	'In a noun1 far far way, a noun2 enters its final noun3',
    'Beeware, the adj1 noun1, and the adj2 noun2 in the noun3',
    "Can you beelieve it? It's the adj1 noun1 in the adj2 noun2.",
    'Giddy-up. Drowning in adj1 noun1, you ponder the noun2.',
    'Woah Nelly! Enter the noun1. How adj1. So adj2.',
    'Tired from your travels you see the adj1 noun1.',
    'Go forth into the adj1 noun1.',
    'Perplexed by the adj1 noun1, you trod along past the adj2, noun2.',
    'Yes! It is the adj1 noun1. You stop for a chat.',
    'Have you gone mad, or is that really the adj1 noun1?',
    'Space dimentia sets in. You begin a conversation with the adj1 noun1.',
]

nouns = [
    'hive',
    'pollen',
    'nectar',
    'wasp',
    'swarm',
    'honey',
    'sting',
    'wax',
    'bee keeper',
    'insecticide',
    'fragrance',
    'jelly',
    'colony',
    'larva',
    'caterpillar',
	'flowers',
	'planet',
	'asteroid',
    'ant',
	'ant hill',
	'ant farm',
	'ant colony',
    'rhino beetle',
    'apiary',
    'weevil',
    'fire ant',
    'stag beetle',
    'garden',
    'honeysuckle',
    'sunflowers',
    'poppies',
    'hummingbird',
    'habitat',
    'anteater',
	'stars',
	'red giant',
	'gravity waves',
	'moon',
	'tornado',
	'hurricane',
	'down pour',
	'nebula',
	'milky way',
	'alien',
	'alien bees',
	'farm',
	'nest',
	'wings',
	'garden',
	'drone',
	'brood',
	'dance',
	'worker',
	'honeycomb',
	'beeswax',
	'civilation',
	'advanced civiliation',
	'gathering',
    'meteor',
    'supernova',
    'super massive black hole',
    'white dwarf',
    'shadow',
    'geyser',
    'volcano',
    'pool of acid',
    'pool of gas',
    'toxic air',
    'rough terrain',
    'floor of glass',
    'butterfly',
    'rain',
	'cosmic rain',
	'cosmic mist',
	'cosmic wind',
    'mist',
    'wind',
    'pulsar',
    'quasar',
    'cosmos',
    'creature',
    'stranger',
    'moon',
    'binary star',
    'dark matter',
    'sky',
    'starlight',
    'observatory',
    'eruptions',
    'solstice',
    'new moon',
    'full moon',
    'twin stars',
    'total eclipse',
    'crater',
    'dwarf planet',
    'meteoroid',
    'cosmic dust',
    'falling star',
]

letters = 'abcdefghijklmnopqrstuvwxyz'

adjectives = [
	'interstellar',
    'honeyliscious',
	'bee-tastic',
	'busy',
	'buzzing',
	'plentiful',
	'angry',
	'aggressive',
	'red',
	'brown',
	'orange',
	'yellow',
	'blue',
	'green',
	'hairy',
	'large',
	'horrific',
	'quick',
	'heavy',
	'dazed',
	'young',
	'drowsy',
	'furious',
	'gentle',
	'drowsy',
	'peace-loving',
	'delightful',
	'gigantic',
	'stange',
	'swift',
	'drunken',
	'dusty',
	'long',
	'black',
	'ordinary',
	'cold',
	'industrious',
	'Italian',
	'German',
	'English',
	'American',
	'French',
	'napoleonic',
	'robust',
	'flaming',
	'dead',
	'lethargic',
	'sleepy',
	'fat',
	'mature',
	'eclectic',
	'homicidal',
	'invisible',
	'beautiful',
	'black and yello',
	'dormant',
	'enormous',
	'metallic',
	'white',
	'merry',
	'distant',
	'Australian',
	'ungrateful',
	'wholesome',
	'active',
	'marvelous',
	'monstrous',
	'benevolent',
	'giddy',
	'ominous',
	'tumultuous',
	'courageous',
	'mathematical',
	'calculating',
	'painful',
	'loyal',
]


def titleGenerator():
	letter = letters[math.floor(random() * len(letters))]

	number = math.floor(random() * 1000)

	return f'hive-{letter}{number}'


def descGenerator():
	template = templates[math.floor(random() * len(templates))]

	def getRandomNoun():
		return nouns[math.floor(random() * len(nouns))]

	def getRandomAdj():
		return adjectives[math.floor(random() * len(adjectives))]

	myStr = template.replace('noun1', getRandomNoun()).replace('noun2', getRandomNoun()).replace('noun3', getRandomNoun()).replace('adj1', getRandomAdj()).replace('adj2', getRandomAdj())

	return myStr
