# Generated by Django 3.0.3 on 2020-02-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='x_coor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y_coor',
            field=models.IntegerField(default=0),
        ),
    ]
