# Generated by Django 3.0.3 on 2020-02-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200204_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Venus Fly Trap', max_length=50)),
                ('description', models.CharField(default='An angry little bugger', max_length=500)),
                ('honeyGained', models.IntegerField(default=2)),
                ('honeyLost', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=1)),
                ('xpGained', models.IntegerField(default=1)),
            ],
        ),
    ]
