# Generated by Django 3.0.3 on 2020-02-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='honey',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=5),
        ),
    ]
