# Generated by Django 3.0.3 on 2020-02-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200205_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adventure.Monster'),
        ),
    ]
